name: GitHub Actions - Gerenciamento de erros
run-name: Running - Gerenciamento de erros
on: [push, workflow_dispatch]

jobs:

  job_1_erro:
    runs-on: ubuntu-20.04
    steps:
        - name: Coment치rio
          run: |
            echo Comentario antes do erro
            exit 1
        - name: Coment치rio
          run: |
            echo Coment치rio ap칩s o erro

  